<?php

use Illuminate\Database\Seeder;

class nilai_kompetensi extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('nilai_umum')->insert([
            'siswa_id' => 1,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 2,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 3,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 4,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 5,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 6,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 7,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 8,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 9,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 10,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 11,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 12,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 13,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 14,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 15,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 16,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 17,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 18,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 19,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('nilai_umum')->insert([
            'siswa_id' => 20,
            'disiplin' => rand(70, 100),
            'kerjasama' => rand(70, 100),
            'kerajinan' => rand(70, 100),
            'tanggung_jawab' => rand(70, 100),
            'sikap' => rand(70, 100),
            'k3' => rand(70, 100),
            'kreatif_kl' => rand(70, 100),
            'persiapan' => rand(70, 100),
            'analisa' => rand(70, 100),
            'perawatan_p' => rand(70, 100),
            'metode_lk' => rand(70, 100),
            'ketetapan_h' => rand(70, 100),
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
